// encode-chatgpt-react/src/views/exception/500/index.tsx
import {useNavigate} from 'react-router-dom';
import {Button} from 'antd';
import Svg404 from '@/icons/svg/404.svg'

const Error500 = () => {
  const navigate = useNavigate();
 return (
  <div className="flex h-full">
      <div className="px-4 m-auto text-center space-y-4 max-[400px]">
        <h1 className="text-4xl text-slate-800 dark:text-neutral-200">
          Sorry,page not found!
        </h1>
        <p className="text-base text-slate-500 dark:text-neutral-400">
          Sorry, we couldn’t find the page you’re looking for. Perhaps you’ve mistyped the URL? Be sure to check your spelling.
        </p>
        <div className='flex justify-center items-center text-center'>
            <div className='w-[300px]'>
               <img src={Svg404} alt="404" />
              </div>       
        </div>
        <Button onClick={() => navigate('/')}>go to Home</Button>
      </div>
  </div>
 )
}

export default Error500

// encode-chatgpt-vue-1.0/src/views/exception/500/index.vue
<script lang="ts" setup>
import { NButton } from 'naive-ui'
import { useRouter } from 'vue-router'
import Icon500 from '@/icons/500.svg'

const router = useRouter()

function goHome() {
  router.push('/')
}
</script>

<template>
  <div class="flex h-full dark:bg-neutral-800">
    <div class="px-4 m-auto space-y-4 text-center max-[400px]">
      <header class="space-y-2">
        <h2 class="text-2xl font-bold text-center text-slate-800 dark:text-neutral-200">
          500
        </h2>
        <p class="text-base text-center text-slate-500 dark:text-slate-500">
          Server error
        </p>
        <div class="flex items-center justify-center text-center">
          <Icon500 class="w-[300px]" />
        </div>
      </header>
      <NButton type="primary" @click="goHome">
        Go to Home
      </NButton>
    </div>
  </div>
</template>
